# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newBlackJackUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Blackjack(object):
    def setupUi(self, Blackjack):
        Blackjack.setObjectName(_fromUtf8("Blackjack"))
        Blackjack.resize(638, 288)
        self.horizontalLayout = QtGui.QHBoxLayout(Blackjack)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.playingSide = QtGui.QVBoxLayout()
        self.playingSide.setObjectName(_fromUtf8("playingSide"))
        self.dealerSide = QtGui.QHBoxLayout()
        self.dealerSide.setObjectName(_fromUtf8("dealerSide"))
        self.dealerLabel = QtGui.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dealerLabel.setFont(font)
        self.dealerLabel.setObjectName(_fromUtf8("dealerLabel"))
        self.dealerSide.addWidget(self.dealerLabel)
        self.dCard_0 = QtGui.QLabel(Blackjack)
        self.dCard_0.setText(_fromUtf8(""))
        self.dCard_0.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_0.setObjectName(_fromUtf8("dCard_0"))
        self.dealerSide.addWidget(self.dCard_0)
        self.dCard_1 = QtGui.QLabel(Blackjack)
        self.dCard_1.setText(_fromUtf8(""))
        self.dCard_1.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_1.setObjectName(_fromUtf8("dCard_1"))
        self.dealerSide.addWidget(self.dCard_1)
        self.dCard_2 = QtGui.QLabel(Blackjack)
        self.dCard_2.setText(_fromUtf8(""))
        self.dCard_2.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_2.setObjectName(_fromUtf8("dCard_2"))
        self.dealerSide.addWidget(self.dCard_2)
        self.dCard_3 = QtGui.QLabel(Blackjack)
        self.dCard_3.setText(_fromUtf8(""))
        self.dCard_3.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_3.setObjectName(_fromUtf8("dCard_3"))
        self.dealerSide.addWidget(self.dCard_3)
        self.dCard_4 = QtGui.QLabel(Blackjack)
        self.dCard_4.setText(_fromUtf8(""))
        self.dCard_4.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_4.setObjectName(_fromUtf8("dCard_4"))
        self.dealerSide.addWidget(self.dCard_4)
        self.dCard_5 = QtGui.QLabel(Blackjack)
        self.dCard_5.setText(_fromUtf8(""))
        self.dCard_5.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_5.setObjectName(_fromUtf8("dCard_5"))
        self.dealerSide.addWidget(self.dCard_5)
        self.dCard_6 = QtGui.QLabel(Blackjack)
        self.dCard_6.setText(_fromUtf8(""))
        self.dCard_6.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_6.setObjectName(_fromUtf8("dCard_6"))
        self.dealerSide.addWidget(self.dCard_6)
        self.dCard_7 = QtGui.QLabel(Blackjack)
        self.dCard_7.setText(_fromUtf8(""))
        self.dCard_7.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_7.setObjectName(_fromUtf8("dCard_7"))
        self.dealerSide.addWidget(self.dCard_7)
        self.dCard_8 = QtGui.QLabel(Blackjack)
        self.dCard_8.setText(_fromUtf8(""))
        self.dCard_8.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_8.setObjectName(_fromUtf8("dCard_8"))
        self.dealerSide.addWidget(self.dCard_8)
        self.dCard_9 = QtGui.QLabel(Blackjack)
        self.dCard_9.setText(_fromUtf8(""))
        self.dCard_9.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_9.setObjectName(_fromUtf8("dCard_9"))
        self.dealerSide.addWidget(self.dCard_9)
        self.playingSide.addLayout(self.dealerSide)
        self.labDealer = QtGui.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labDealer.setFont(font)
        self.labDealer.setObjectName(_fromUtf8("labDealer"))
        self.playingSide.addWidget(self.labDealer)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.playingSide.addItem(spacerItem)
        self.playerSide = QtGui.QHBoxLayout()
        self.playerSide.setObjectName(_fromUtf8("playerSide"))
        self.playerLabel = QtGui.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.playerLabel.setFont(font)
        self.playerLabel.setObjectName(_fromUtf8("playerLabel"))
        self.playerSide.addWidget(self.playerLabel)
        self.pCard_0 = QtGui.QLabel(Blackjack)
        self.pCard_0.setText(_fromUtf8(""))
        self.pCard_0.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_0.setObjectName(_fromUtf8("pCard_0"))
        self.playerSide.addWidget(self.pCard_0)
        self.pCard_1 = QtGui.QLabel(Blackjack)
        self.pCard_1.setText(_fromUtf8(""))
        self.pCard_1.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_1.setObjectName(_fromUtf8("pCard_1"))
        self.playerSide.addWidget(self.pCard_1)
        self.pCard_2 = QtGui.QLabel(Blackjack)
        self.pCard_2.setText(_fromUtf8(""))
        self.pCard_2.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_2.setObjectName(_fromUtf8("pCard_2"))
        self.playerSide.addWidget(self.pCard_2)
        self.pCard_3 = QtGui.QLabel(Blackjack)
        self.pCard_3.setText(_fromUtf8(""))
        self.pCard_3.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_3.setObjectName(_fromUtf8("pCard_3"))
        self.playerSide.addWidget(self.pCard_3)
        self.pCard_4 = QtGui.QLabel(Blackjack)
        self.pCard_4.setText(_fromUtf8(""))
        self.pCard_4.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_4.setObjectName(_fromUtf8("pCard_4"))
        self.playerSide.addWidget(self.pCard_4)
        self.pCard_5 = QtGui.QLabel(Blackjack)
        self.pCard_5.setText(_fromUtf8(""))
        self.pCard_5.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_5.setObjectName(_fromUtf8("pCard_5"))
        self.playerSide.addWidget(self.pCard_5)
        self.pCard_6 = QtGui.QLabel(Blackjack)
        self.pCard_6.setText(_fromUtf8(""))
        self.pCard_6.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_6.setObjectName(_fromUtf8("pCard_6"))
        self.playerSide.addWidget(self.pCard_6)
        self.pCard_7 = QtGui.QLabel(Blackjack)
        self.pCard_7.setText(_fromUtf8(""))
        self.pCard_7.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_7.setObjectName(_fromUtf8("pCard_7"))
        self.playerSide.addWidget(self.pCard_7)
        self.pCard_8 = QtGui.QLabel(Blackjack)
        self.pCard_8.setText(_fromUtf8(""))
        self.pCard_8.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_8.setObjectName(_fromUtf8("pCard_8"))
        self.playerSide.addWidget(self.pCard_8)
        self.pCard_9 = QtGui.QLabel(Blackjack)
        self.pCard_9.setText(_fromUtf8(""))
        self.pCard_9.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_9.setObjectName(_fromUtf8("pCard_9"))
        self.playerSide.addWidget(self.pCard_9)
        self.playingSide.addLayout(self.playerSide)
        self.labPlayer = QtGui.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labPlayer.setFont(font)
        self.labPlayer.setObjectName(_fromUtf8("labPlayer"))
        self.playingSide.addWidget(self.labPlayer)
        self.horizontalLayout.addLayout(self.playingSide)
        self.bettingSide = QtGui.QVBoxLayout()
        self.bettingSide.setObjectName(_fromUtf8("bettingSide"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.bettingSide.addItem(spacerItem1)
        self.moneyLayout = QtGui.QHBoxLayout()
        self.moneyLayout.setObjectName(_fromUtf8("moneyLayout"))
        self.moneyLabel_3 = QtGui.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.moneyLabel_3.setFont(font)
        self.moneyLabel_3.setObjectName(_fromUtf8("moneyLabel_3"))
        self.moneyLayout.addWidget(self.moneyLabel_3)
        self.labMoney = QtGui.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labMoney.setFont(font)
        self.labMoney.setObjectName(_fromUtf8("labMoney"))
        self.moneyLayout.addWidget(self.labMoney)
        self.bettingSide.addLayout(self.moneyLayout)
        self.betLabel = QtGui.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.betLabel.setFont(font)
        self.betLabel.setObjectName(_fromUtf8("betLabel"))
        self.bettingSide.addWidget(self.betLabel)
        self.betSpinBox = QtGui.QSpinBox(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.betSpinBox.setFont(font)
        self.betSpinBox.setMinimum(1)
        self.betSpinBox.setMaximum(99999999)
        self.betSpinBox.setObjectName(_fromUtf8("betSpinBox"))
        self.bettingSide.addWidget(self.betSpinBox)
        self.labWarning = QtGui.QLabel(Blackjack)
        self.labWarning.setText(_fromUtf8(""))
        self.labWarning.setObjectName(_fromUtf8("labWarning"))
        self.bettingSide.addWidget(self.labWarning)
        self.btnBet = QtGui.QPushButton(Blackjack)
        self.btnBet.setObjectName(_fromUtf8("btnBet"))
        self.bettingSide.addWidget(self.btnBet)
        self.btnDouble = QtGui.QPushButton(Blackjack)
        self.btnDouble.setObjectName(_fromUtf8("btnDouble"))
        self.bettingSide.addWidget(self.btnDouble)
        self.btnHit = QtGui.QPushButton(Blackjack)
        self.btnHit.setObjectName(_fromUtf8("btnHit"))
        self.bettingSide.addWidget(self.btnHit)
        self.btnStay = QtGui.QPushButton(Blackjack)
        self.btnStay.setObjectName(_fromUtf8("btnStay"))
        self.bettingSide.addWidget(self.btnStay)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.bettingSide.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.bettingSide)

        self.retranslateUi(Blackjack)
        QtCore.QMetaObject.connectSlotsByName(Blackjack)

    def retranslateUi(self, Blackjack):
        Blackjack.setWindowTitle(_translate("Blackjack", "Form", None))
        self.dealerLabel.setText(_translate("Blackjack", "Dealer:", None))
        self.labDealer.setText(_translate("Blackjack", "0", None))
        self.playerLabel.setText(_translate("Blackjack", "Player:", None))
        self.labPlayer.setText(_translate("Blackjack", "0", None))
        self.moneyLabel_3.setText(_translate("Blackjack", "Money: $", None))
        self.labMoney.setText(_translate("Blackjack", "500", None))
        self.betLabel.setText(_translate("Blackjack", "Enter amount to bet:", None))
        self.btnBet.setText(_translate("Blackjack", "Enter Bet", None))
        self.btnDouble.setText(_translate("Blackjack", "Double", None))
        self.btnHit.setText(_translate("Blackjack", "Hit", None))
        self.btnStay.setText(_translate("Blackjack", "Stay", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Blackjack = QtGui.QWidget()
    ui = Ui_Blackjack()
    ui.setupUi(Blackjack)
    Blackjack.show()
    sys.exit(app.exec_())

