# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newBlackJacUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BlackJack(object):
    def setupUi(self, BlackJack):
        BlackJack.setObjectName(_fromUtf8("BlackJack"))
        BlackJack.resize(638, 288)
        self.horizontalLayout_3 = QtGui.QHBoxLayout(BlackJack)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.playingSide = QtGui.QVBoxLayout()
        self.playingSide.setObjectName(_fromUtf8("playingSide"))
        self.dealerSide = QtGui.QHBoxLayout()
        self.dealerSide.setObjectName(_fromUtf8("dealerSide"))
        self.dealerLabel = QtGui.QLabel(BlackJack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dealerLabel.setFont(font)
        self.dealerLabel.setObjectName(_fromUtf8("dealerLabel"))
        self.dealerSide.addWidget(self.dealerLabel)
        self.dCard_0 = QtGui.QLabel(BlackJack)
        self.dCard_0.setText(_fromUtf8(""))
        self.dCard_0.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_0.setObjectName(_fromUtf8("dCard_0"))
        self.dealerSide.addWidget(self.dCard_0)
        self.dCard_1 = QtGui.QLabel(BlackJack)
        self.dCard_1.setText(_fromUtf8(""))
        self.dCard_1.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_1.setObjectName(_fromUtf8("dCard_1"))
        self.dealerSide.addWidget(self.dCard_1)
        self.dCard_2 = QtGui.QLabel(BlackJack)
        self.dCard_2.setText(_fromUtf8(""))
        self.dCard_2.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_2.setObjectName(_fromUtf8("dCard_2"))
        self.dealerSide.addWidget(self.dCard_2)
        self.dCard_3 = QtGui.QLabel(BlackJack)
        self.dCard_3.setText(_fromUtf8(""))
        self.dCard_3.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_3.setObjectName(_fromUtf8("dCard_3"))
        self.dealerSide.addWidget(self.dCard_3)
        self.dCard_4 = QtGui.QLabel(BlackJack)
        self.dCard_4.setText(_fromUtf8(""))
        self.dCard_4.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.dCard_4.setObjectName(_fromUtf8("dCard_4"))
        self.dealerSide.addWidget(self.dCard_4)
        self.playingSide.addLayout(self.dealerSide)
        self.dCardAmt = QtGui.QLabel(BlackJack)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dCardAmt.setFont(font)
        self.dCardAmt.setObjectName(_fromUtf8("dCardAmt"))
        self.playingSide.addWidget(self.dCardAmt)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.playingSide.addItem(spacerItem)
        self.playerSide = QtGui.QHBoxLayout()
        self.playerSide.setObjectName(_fromUtf8("playerSide"))
        self.playerLabel = QtGui.QLabel(BlackJack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.playerLabel.setFont(font)
        self.playerLabel.setObjectName(_fromUtf8("playerLabel"))
        self.playerSide.addWidget(self.playerLabel)
        self.pCard_0 = QtGui.QLabel(BlackJack)
        self.pCard_0.setText(_fromUtf8(""))
        self.pCard_0.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_0.setObjectName(_fromUtf8("pCard_0"))
        self.playerSide.addWidget(self.pCard_0)
        self.pCard_1 = QtGui.QLabel(BlackJack)
        self.pCard_1.setText(_fromUtf8(""))
        self.pCard_1.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_1.setObjectName(_fromUtf8("pCard_1"))
        self.playerSide.addWidget(self.pCard_1)
        self.pCard_2 = QtGui.QLabel(BlackJack)
        self.pCard_2.setText(_fromUtf8(""))
        self.pCard_2.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_2.setObjectName(_fromUtf8("pCard_2"))
        self.playerSide.addWidget(self.pCard_2)
        self.pCard_3 = QtGui.QLabel(BlackJack)
        self.pCard_3.setText(_fromUtf8(""))
        self.pCard_3.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_3.setObjectName(_fromUtf8("pCard_3"))
        self.playerSide.addWidget(self.pCard_3)
        self.pCard_4 = QtGui.QLabel(BlackJack)
        self.pCard_4.setText(_fromUtf8(""))
        self.pCard_4.setPixmap(QtGui.QPixmap(_fromUtf8("../cards/back.png")))
        self.pCard_4.setObjectName(_fromUtf8("pCard_4"))
        self.playerSide.addWidget(self.pCard_4)
        self.playingSide.addLayout(self.playerSide)
        self.pCardAmt = QtGui.QLabel(BlackJack)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pCardAmt.setFont(font)
        self.pCardAmt.setObjectName(_fromUtf8("pCardAmt"))
        self.playingSide.addWidget(self.pCardAmt)
        self.horizontalLayout_3.addLayout(self.playingSide)
        self.bettingSide = QtGui.QVBoxLayout()
        self.bettingSide.setObjectName(_fromUtf8("bettingSide"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.bettingSide.addItem(spacerItem1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.moneyLabel_3 = QtGui.QLabel(BlackJack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.moneyLabel_3.setFont(font)
        self.moneyLabel_3.setObjectName(_fromUtf8("moneyLabel_3"))
        self.horizontalLayout.addWidget(self.moneyLabel_3)
        self.labMoney = QtGui.QLabel(BlackJack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labMoney.setFont(font)
        self.labMoney.setObjectName(_fromUtf8("labMoney"))
        self.horizontalLayout.addWidget(self.labMoney)
        self.bettingSide.addLayout(self.horizontalLayout)
        self.betLabel = QtGui.QLabel(BlackJack)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.betLabel.setFont(font)
        self.betLabel.setObjectName(_fromUtf8("betLabel"))
        self.bettingSide.addWidget(self.betLabel)
        self.betDoubleSpinBox = QtGui.QDoubleSpinBox(BlackJack)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.betDoubleSpinBox.setFont(font)
        self.betDoubleSpinBox.setMaximum(9999999.0)
        self.betDoubleSpinBox.setProperty("value", 1.0)
        self.betDoubleSpinBox.setObjectName(_fromUtf8("betDoubleSpinBox"))
        self.bettingSide.addWidget(self.betDoubleSpinBox)
        self.btnBet = QtGui.QPushButton(BlackJack)
        self.btnBet.setObjectName(_fromUtf8("btnBet"))
        self.bettingSide.addWidget(self.btnBet)
        self.btnDouble = QtGui.QPushButton(BlackJack)
        self.btnDouble.setObjectName(_fromUtf8("btnDouble"))
        self.bettingSide.addWidget(self.btnDouble)
        self.btnHit = QtGui.QPushButton(BlackJack)
        self.btnHit.setObjectName(_fromUtf8("btnHit"))
        self.bettingSide.addWidget(self.btnHit)
        self.btnStay = QtGui.QPushButton(BlackJack)
        self.btnStay.setObjectName(_fromUtf8("btnStay"))
        self.bettingSide.addWidget(self.btnStay)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.bettingSide.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.bettingSide)
        self.pCard_2.raise_()
        self.pCard_3.raise_()
        self.pCard_0.raise_()
        self.pCard_4.raise_()
        self.pCard_1.raise_()
        self.playerLabel.raise_()
        self.dCard_1.raise_()
        self.dCard_3.raise_()
        self.dCard_4.raise_()
        self.dCard_2.raise_()
        self.dCard_0.raise_()

        self.retranslateUi(BlackJack)
        QtCore.QMetaObject.connectSlotsByName(BlackJack)

    def retranslateUi(self, BlackJack):
        BlackJack.setWindowTitle(_translate("BlackJack", "Form", None))
        self.dealerLabel.setText(_translate("BlackJack", "Dealer:", None))
        self.dCardAmt.setText(_translate("BlackJack", "0", None))
        self.playerLabel.setText(_translate("BlackJack", "Player:", None))
        self.pCardAmt.setText(_translate("BlackJack", "0", None))
        self.moneyLabel_3.setText(_translate("BlackJack", "Money:", None))
        self.labMoney.setText(_translate("BlackJack", "500", None))
        self.betLabel.setText(_translate("BlackJack", "Enter amount to bet:", None))
        self.btnBet.setText(_translate("BlackJack", "Enter Bet", None))
        self.btnDouble.setText(_translate("BlackJack", "Double", None))
        self.btnHit.setText(_translate("BlackJack", "Hit", None))
        self.btnStay.setText(_translate("BlackJack", "Stay", None))

